# Generated by Django 5.2.2 on 2025-06-22 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0007_entidad_solicitud_entidad_and_more'),
        ('users', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='Registro.entidad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('director', 'Director General'), ('especialista', 'Especialista'), ('invitado', 'Invitado')], default='invitado', max_length=20),
        ),
    ]
