# Generated by Django 4.2.7 on 2024-11-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.IntegerField()),
                ('numero_certificado', models.CharField(max_length=10)),
                ('nombre_apellidos', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('fecha_entrada', models.DateField()),
                ('personal_atencion' , models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('asentamiento', models.CharField(max_length=50)),
                ('persona', models.CharField(max_length=50)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('tiempo_proceso', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
