# Generated by Django 4.2.7 on 2024-11-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='numero_orden',
            field=models.CharField(max_length=10),
        ),
      
    ]
