# Generated by Django 4.2.7 on 2024-11-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_alter_solicitud_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(blank=True),
        ),
    ]
