# Generated by Django 4.2.7 on 2024-11-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_alter_solicitud_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='solicitudes',
            field=models.ManyToManyField(related_name='solicitudes', to='Registro.solicitud'),
        ),
    ]
