# Generated by Django 4.2.7 on 2025-06-05 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_solicitud_solicitudes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='solicitudes',
        ),
    ]
