# Generated by Django 4.2.7 on 2025-06-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_remove_solicitud_solicitudes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
